### ISSUE TITLE
Error report: Not Found

### ISSUE THREAD

**Issue by erlend-sh** [wiki-hub/jekyll-anon#7]
Getting this when I try to hit submit:

<img width="1142" alt="screen shot 2015-09-09 at 01 31 15" src="https://cloud.githubusercontent.com/assets/583842/9750015/d4c5c61a-5692-11e5-9bde-0e5a12d2b4c9.png">

**Comment by pull-master** [comment]
Thanks. It should be working now.

The problem was caused by me changing default branch on this repository. I figured there's no point being on gh-pages branch if it's hosted on divshot. But the fork the pull-requests was on was still using the gh-pages branch as default. It's been changed now.

**Comment by mushishi78** [comment]
Thanks. It should be working now. The problem was caused by me changing default branch on this repository, but not updating the forked repository that the commits were coming from.
